.\" @(#)$RCSfile: gfal2_version.man,v $ $Revision: 2 $ $Date: 2012/04/13 13:09:16 $ CERN Adrien Devresse
.\" Copyright (C) 2012 by CERN
.\" All rights reserved
.\"
.TH GFAL2_VERSION 1 "$Date: 2012/04/13 13:09:16 $" GFAL 2.0 "Library Utility"
.SH NAME
gfal2_version \- Version tool for gfal2
.SH SYNOPSIS
\fBgfal2_version\fR
.sp
.BI "gfal2_version
.SH DESCRIPTION
Simple utility printing the current version of the gfal2 library.

