/* soapDelegationSoapBindingProxy.h
   Generated by gSOAP 2.7.13 from /root/build/gfal2/src/common/http/delegation.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapDelegationSoapBindingProxy_H
#define soapDelegationSoapBindingProxy_H
#include "soapH.h"
class DelegationSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'DelegationSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	DelegationSoapBinding()
	{ soap = soap_new(); endpoint = "https://localhost:8443/glite-security-delegation"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"tns", "http://www.gridsite.org/namespaces/delegation-1", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~DelegationSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'getProxyReq' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__getProxyReq(std::string _delegationID, struct tns__getProxyReqResponse &_param_1) { return soap ? soap_call_tns__getProxyReq(soap, endpoint, NULL, _delegationID, _param_1) : SOAP_EOM; };
	/// Invoke 'getNewProxyReq' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__getNewProxyReq(struct tns__getNewProxyReqResponse &_param_2) { return soap ? soap_call_tns__getNewProxyReq(soap, endpoint, NULL, _param_2) : SOAP_EOM; };
	/// Invoke 'renewProxyReq' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__renewProxyReq(std::string _delegationID, struct tns__renewProxyReqResponse &_param_3) { return soap ? soap_call_tns__renewProxyReq(soap, endpoint, NULL, _delegationID, _param_3) : SOAP_EOM; };
	/// Invoke 'putProxy' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__putProxy(std::string _delegationID, std::string _proxy, struct tns__putProxyResponse &_param_4) { return soap ? soap_call_tns__putProxy(soap, endpoint, NULL, _delegationID, _proxy, _param_4) : SOAP_EOM; };
	/// Invoke 'getTerminationTime' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__getTerminationTime(std::string _delegationID, struct tns__getTerminationTimeResponse &_param_5) { return soap ? soap_call_tns__getTerminationTime(soap, endpoint, NULL, _delegationID, _param_5) : SOAP_EOM; };
	/// Invoke 'destroy' of service 'DelegationSoapBinding' and return error code (or SOAP_OK)
	virtual int tns__destroy(std::string _delegationID, struct tns__destroyResponse &_param_6) { return soap ? soap_call_tns__destroy(soap, endpoint, NULL, _delegationID, _param_6) : SOAP_EOM; };
};
#endif
