/* soapH.h
   Generated by gSOAP 2.7.13 from /root/build/gfal2/src/common/http/delegation.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__NewProxyReq
#define SOAP_TYPE_tns__NewProxyReq (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__NewProxyReq(struct soap*, const char*, int, const tns__NewProxyReq *, const char*);
SOAP_FMAC3 tns__NewProxyReq * SOAP_FMAC4 soap_get_tns__NewProxyReq(struct soap*, tns__NewProxyReq *, const char*, const char*);
SOAP_FMAC3 tns__NewProxyReq * SOAP_FMAC4 soap_in_tns__NewProxyReq(struct soap*, const char*, tns__NewProxyReq *, const char*);

#define soap_new_tns__NewProxyReq(soap, n) soap_instantiate_tns__NewProxyReq(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__NewProxyReq(soap, p) soap_delete(soap, p)

SOAP_FMAC3 tns__NewProxyReq * SOAP_FMAC4 soap_instantiate_tns__NewProxyReq(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__NewProxyReq(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__DelegationExceptionType
#define SOAP_TYPE_tns__DelegationExceptionType (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__DelegationExceptionType(struct soap*, const char*, int, const tns__DelegationExceptionType *, const char*);
SOAP_FMAC3 tns__DelegationExceptionType * SOAP_FMAC4 soap_get_tns__DelegationExceptionType(struct soap*, tns__DelegationExceptionType *, const char*, const char*);
SOAP_FMAC3 tns__DelegationExceptionType * SOAP_FMAC4 soap_in_tns__DelegationExceptionType(struct soap*, const char*, tns__DelegationExceptionType *, const char*);

#define soap_new_tns__DelegationExceptionType(soap, n) soap_instantiate_tns__DelegationExceptionType(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__DelegationExceptionType(soap, p) soap_delete(soap, p)

SOAP_FMAC3 tns__DelegationExceptionType * SOAP_FMAC4 soap_instantiate_tns__DelegationExceptionType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__DelegationExceptionType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_tns__destroy
#define SOAP_TYPE_tns__destroy (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__destroy(struct soap*, struct tns__destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__destroy(struct soap*, const struct tns__destroy *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__destroy(struct soap*, const struct tns__destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__destroy(struct soap*, const char*, int, const struct tns__destroy *, const char*);
SOAP_FMAC3 struct tns__destroy * SOAP_FMAC4 soap_get_tns__destroy(struct soap*, struct tns__destroy *, const char*, const char*);
SOAP_FMAC3 struct tns__destroy * SOAP_FMAC4 soap_in_tns__destroy(struct soap*, const char*, struct tns__destroy *, const char*);

#define soap_new_tns__destroy(soap, n) soap_instantiate_tns__destroy(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__destroy(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__destroy * SOAP_FMAC4 soap_instantiate_tns__destroy(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__destroy(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__destroyResponse
#define SOAP_TYPE_tns__destroyResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__destroyResponse(struct soap*, struct tns__destroyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__destroyResponse(struct soap*, const struct tns__destroyResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__destroyResponse(struct soap*, const struct tns__destroyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__destroyResponse(struct soap*, const char*, int, const struct tns__destroyResponse *, const char*);
SOAP_FMAC3 struct tns__destroyResponse * SOAP_FMAC4 soap_get_tns__destroyResponse(struct soap*, struct tns__destroyResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__destroyResponse * SOAP_FMAC4 soap_in_tns__destroyResponse(struct soap*, const char*, struct tns__destroyResponse *, const char*);

#define soap_new_tns__destroyResponse(soap, n) soap_instantiate_tns__destroyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__destroyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__destroyResponse * SOAP_FMAC4 soap_instantiate_tns__destroyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__destroyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getTerminationTime
#define SOAP_TYPE_tns__getTerminationTime (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getTerminationTime(struct soap*, struct tns__getTerminationTime *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getTerminationTime(struct soap*, const struct tns__getTerminationTime *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getTerminationTime(struct soap*, const struct tns__getTerminationTime *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getTerminationTime(struct soap*, const char*, int, const struct tns__getTerminationTime *, const char*);
SOAP_FMAC3 struct tns__getTerminationTime * SOAP_FMAC4 soap_get_tns__getTerminationTime(struct soap*, struct tns__getTerminationTime *, const char*, const char*);
SOAP_FMAC3 struct tns__getTerminationTime * SOAP_FMAC4 soap_in_tns__getTerminationTime(struct soap*, const char*, struct tns__getTerminationTime *, const char*);

#define soap_new_tns__getTerminationTime(soap, n) soap_instantiate_tns__getTerminationTime(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getTerminationTime(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getTerminationTime * SOAP_FMAC4 soap_instantiate_tns__getTerminationTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getTerminationTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getTerminationTimeResponse
#define SOAP_TYPE_tns__getTerminationTimeResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getTerminationTimeResponse(struct soap*, struct tns__getTerminationTimeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getTerminationTimeResponse(struct soap*, const struct tns__getTerminationTimeResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getTerminationTimeResponse(struct soap*, const struct tns__getTerminationTimeResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getTerminationTimeResponse(struct soap*, const char*, int, const struct tns__getTerminationTimeResponse *, const char*);
SOAP_FMAC3 struct tns__getTerminationTimeResponse * SOAP_FMAC4 soap_get_tns__getTerminationTimeResponse(struct soap*, struct tns__getTerminationTimeResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getTerminationTimeResponse * SOAP_FMAC4 soap_in_tns__getTerminationTimeResponse(struct soap*, const char*, struct tns__getTerminationTimeResponse *, const char*);

#define soap_new_tns__getTerminationTimeResponse(soap, n) soap_instantiate_tns__getTerminationTimeResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getTerminationTimeResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getTerminationTimeResponse * SOAP_FMAC4 soap_instantiate_tns__getTerminationTimeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getTerminationTimeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__putProxy
#define SOAP_TYPE_tns__putProxy (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__putProxy(struct soap*, struct tns__putProxy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__putProxy(struct soap*, const struct tns__putProxy *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__putProxy(struct soap*, const struct tns__putProxy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__putProxy(struct soap*, const char*, int, const struct tns__putProxy *, const char*);
SOAP_FMAC3 struct tns__putProxy * SOAP_FMAC4 soap_get_tns__putProxy(struct soap*, struct tns__putProxy *, const char*, const char*);
SOAP_FMAC3 struct tns__putProxy * SOAP_FMAC4 soap_in_tns__putProxy(struct soap*, const char*, struct tns__putProxy *, const char*);

#define soap_new_tns__putProxy(soap, n) soap_instantiate_tns__putProxy(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__putProxy(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__putProxy * SOAP_FMAC4 soap_instantiate_tns__putProxy(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__putProxy(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__putProxyResponse
#define SOAP_TYPE_tns__putProxyResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__putProxyResponse(struct soap*, struct tns__putProxyResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__putProxyResponse(struct soap*, const struct tns__putProxyResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__putProxyResponse(struct soap*, const struct tns__putProxyResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__putProxyResponse(struct soap*, const char*, int, const struct tns__putProxyResponse *, const char*);
SOAP_FMAC3 struct tns__putProxyResponse * SOAP_FMAC4 soap_get_tns__putProxyResponse(struct soap*, struct tns__putProxyResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__putProxyResponse * SOAP_FMAC4 soap_in_tns__putProxyResponse(struct soap*, const char*, struct tns__putProxyResponse *, const char*);

#define soap_new_tns__putProxyResponse(soap, n) soap_instantiate_tns__putProxyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__putProxyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__putProxyResponse * SOAP_FMAC4 soap_instantiate_tns__putProxyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__putProxyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__renewProxyReq
#define SOAP_TYPE_tns__renewProxyReq (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__renewProxyReq(struct soap*, struct tns__renewProxyReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__renewProxyReq(struct soap*, const struct tns__renewProxyReq *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__renewProxyReq(struct soap*, const struct tns__renewProxyReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__renewProxyReq(struct soap*, const char*, int, const struct tns__renewProxyReq *, const char*);
SOAP_FMAC3 struct tns__renewProxyReq * SOAP_FMAC4 soap_get_tns__renewProxyReq(struct soap*, struct tns__renewProxyReq *, const char*, const char*);
SOAP_FMAC3 struct tns__renewProxyReq * SOAP_FMAC4 soap_in_tns__renewProxyReq(struct soap*, const char*, struct tns__renewProxyReq *, const char*);

#define soap_new_tns__renewProxyReq(soap, n) soap_instantiate_tns__renewProxyReq(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__renewProxyReq(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__renewProxyReq * SOAP_FMAC4 soap_instantiate_tns__renewProxyReq(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__renewProxyReq(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__renewProxyReqResponse
#define SOAP_TYPE_tns__renewProxyReqResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__renewProxyReqResponse(struct soap*, struct tns__renewProxyReqResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__renewProxyReqResponse(struct soap*, const struct tns__renewProxyReqResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__renewProxyReqResponse(struct soap*, const struct tns__renewProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__renewProxyReqResponse(struct soap*, const char*, int, const struct tns__renewProxyReqResponse *, const char*);
SOAP_FMAC3 struct tns__renewProxyReqResponse * SOAP_FMAC4 soap_get_tns__renewProxyReqResponse(struct soap*, struct tns__renewProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__renewProxyReqResponse * SOAP_FMAC4 soap_in_tns__renewProxyReqResponse(struct soap*, const char*, struct tns__renewProxyReqResponse *, const char*);

#define soap_new_tns__renewProxyReqResponse(soap, n) soap_instantiate_tns__renewProxyReqResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__renewProxyReqResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__renewProxyReqResponse * SOAP_FMAC4 soap_instantiate_tns__renewProxyReqResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__renewProxyReqResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getNewProxyReq
#define SOAP_TYPE_tns__getNewProxyReq (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getNewProxyReq(struct soap*, struct tns__getNewProxyReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getNewProxyReq(struct soap*, const struct tns__getNewProxyReq *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getNewProxyReq(struct soap*, const struct tns__getNewProxyReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNewProxyReq(struct soap*, const char*, int, const struct tns__getNewProxyReq *, const char*);
SOAP_FMAC3 struct tns__getNewProxyReq * SOAP_FMAC4 soap_get_tns__getNewProxyReq(struct soap*, struct tns__getNewProxyReq *, const char*, const char*);
SOAP_FMAC3 struct tns__getNewProxyReq * SOAP_FMAC4 soap_in_tns__getNewProxyReq(struct soap*, const char*, struct tns__getNewProxyReq *, const char*);

#define soap_new_tns__getNewProxyReq(soap, n) soap_instantiate_tns__getNewProxyReq(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getNewProxyReq(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getNewProxyReq * SOAP_FMAC4 soap_instantiate_tns__getNewProxyReq(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getNewProxyReq(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getNewProxyReqResponse
#define SOAP_TYPE_tns__getNewProxyReqResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getNewProxyReqResponse(struct soap*, struct tns__getNewProxyReqResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getNewProxyReqResponse(struct soap*, const struct tns__getNewProxyReqResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getNewProxyReqResponse(struct soap*, const struct tns__getNewProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getNewProxyReqResponse(struct soap*, const char*, int, const struct tns__getNewProxyReqResponse *, const char*);
SOAP_FMAC3 struct tns__getNewProxyReqResponse * SOAP_FMAC4 soap_get_tns__getNewProxyReqResponse(struct soap*, struct tns__getNewProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getNewProxyReqResponse * SOAP_FMAC4 soap_in_tns__getNewProxyReqResponse(struct soap*, const char*, struct tns__getNewProxyReqResponse *, const char*);

#define soap_new_tns__getNewProxyReqResponse(soap, n) soap_instantiate_tns__getNewProxyReqResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getNewProxyReqResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getNewProxyReqResponse * SOAP_FMAC4 soap_instantiate_tns__getNewProxyReqResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getNewProxyReqResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getProxyReq
#define SOAP_TYPE_tns__getProxyReq (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getProxyReq(struct soap*, struct tns__getProxyReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getProxyReq(struct soap*, const struct tns__getProxyReq *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getProxyReq(struct soap*, const struct tns__getProxyReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getProxyReq(struct soap*, const char*, int, const struct tns__getProxyReq *, const char*);
SOAP_FMAC3 struct tns__getProxyReq * SOAP_FMAC4 soap_get_tns__getProxyReq(struct soap*, struct tns__getProxyReq *, const char*, const char*);
SOAP_FMAC3 struct tns__getProxyReq * SOAP_FMAC4 soap_in_tns__getProxyReq(struct soap*, const char*, struct tns__getProxyReq *, const char*);

#define soap_new_tns__getProxyReq(soap, n) soap_instantiate_tns__getProxyReq(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getProxyReq(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getProxyReq * SOAP_FMAC4 soap_instantiate_tns__getProxyReq(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getProxyReq(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_tns__getProxyReqResponse
#define SOAP_TYPE_tns__getProxyReqResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tns__getProxyReqResponse(struct soap*, struct tns__getProxyReqResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tns__getProxyReqResponse(struct soap*, const struct tns__getProxyReqResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tns__getProxyReqResponse(struct soap*, const struct tns__getProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tns__getProxyReqResponse(struct soap*, const char*, int, const struct tns__getProxyReqResponse *, const char*);
SOAP_FMAC3 struct tns__getProxyReqResponse * SOAP_FMAC4 soap_get_tns__getProxyReqResponse(struct soap*, struct tns__getProxyReqResponse *, const char*, const char*);
SOAP_FMAC3 struct tns__getProxyReqResponse * SOAP_FMAC4 soap_in_tns__getProxyReqResponse(struct soap*, const char*, struct tns__getProxyReqResponse *, const char*);

#define soap_new_tns__getProxyReqResponse(soap, n) soap_instantiate_tns__getProxyReqResponse(soap, n, NULL, NULL, NULL)


#define soap_delete_tns__getProxyReqResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct tns__getProxyReqResponse * SOAP_FMAC4 soap_instantiate_tns__getProxyReqResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_tns__getProxyReqResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTotns__NewProxyReq
#define SOAP_TYPE_PointerTotns__NewProxyReq (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__NewProxyReq(struct soap*, tns__NewProxyReq *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__NewProxyReq(struct soap*, tns__NewProxyReq *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__NewProxyReq(struct soap*, const char *, int, tns__NewProxyReq *const*, const char *);
SOAP_FMAC3 tns__NewProxyReq ** SOAP_FMAC4 soap_get_PointerTotns__NewProxyReq(struct soap*, tns__NewProxyReq **, const char*, const char*);
SOAP_FMAC3 tns__NewProxyReq ** SOAP_FMAC4 soap_in_PointerTotns__NewProxyReq(struct soap*, const char*, tns__NewProxyReq **, const char*);

#ifndef SOAP_TYPE_PointerTotns__DelegationExceptionType
#define SOAP_TYPE_PointerTotns__DelegationExceptionType (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotns__DelegationExceptionType(struct soap*, tns__DelegationExceptionType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotns__DelegationExceptionType(struct soap*, tns__DelegationExceptionType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotns__DelegationExceptionType(struct soap*, const char *, int, tns__DelegationExceptionType *const*, const char *);
SOAP_FMAC3 tns__DelegationExceptionType ** SOAP_FMAC4 soap_get_PointerTotns__DelegationExceptionType(struct soap*, tns__DelegationExceptionType **, const char*, const char*);
SOAP_FMAC3 tns__DelegationExceptionType ** SOAP_FMAC4 soap_in_PointerTotns__DelegationExceptionType(struct soap*, const char*, tns__DelegationExceptionType **, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
