.\" @(#)$RCSfile: gfal_internal_free.man,v $ $Revision: 1.3 $ $Date: 2008/06/05 13:09:16 $ CERN Remi Mollon
.\" Copyright (C) 2007 by CERN
.\" All rights reserved
.\"
.TH GFAL_INTERNAL_FREE 3 "$Date: 2008/06/05 13:09:16 $" GFAL "Library Functions"
.SH NAME
gfal_internal_free \- frees gfal_internal objects

.SH SYNOPSIS
\fB#include "gfal_api.h"\fR
.sp
.BI "void gfal_internal_free (gfal_internal gfal);

.SH DESCRIPTION
.B gfal_internal_free
frees 
.B gfal_internal
objects with all results which are included. But it
.B DOESN'T FREE
parts of the initial 
.B gfal_request
object which are used in it.
.TP
.I gfal
.B gfal_internal
object to free.

.SH SEE ALSO
.BR gfal (3),
.BR gfal_request_new (3),
.BR gfal_internal_free (3),
.BR gfal_init (3),
.BR gfal_deletesurls (3),
.BR gfal_removedir (3),
.BR gfal_turlsfromsurls (3),
.BR gfal_ls (3),
.BR gfal_get (3),
.BR gfal_getstatus (3),
.BR gfal_prestage (3),
.BR gfal_prestagestatus (3),
.BR gfal_pin (3),
.BR gfal_release (3),
.BR gfal_abortrequest (3),
.BR gfal_abortfiles (3),
.BR gfal_set_xfer_done (3),
.BR gfal_set_xfer_running (3),
.BR gfal_get_ids (3),
.BR gfal_set_ids (3),
.BR gfal_get_results (3),
